version: '3.8'

services:
  envkey-lite:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Application Configuration
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - APP_NAME=EnvKey Lite
      - APP_VERSION=1.0.0
      
      # Database Configuration
      - DATABASE_DIR=/app/data
      
      # Security Configuration (CHANGE THESE IN PRODUCTION!)
      - JWT_SECRET=${JWT_SECRET:-CHANGE_THIS_TO_A_SECURE_64_CHARACTER_JWT_SECRET_FOR_PRODUCTION}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-CHANGE_THIS_TO_A_SECURE_32_CHARACTER_ENCRYPTION_KEY}
      - API_KEY_PREFIX=envkey_
      
      # CORS Configuration
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      
      # Logging Configuration
      - LOG_LEVEL=warn
      
      # Rate Limiting (stricter for production)
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=50
      
      # Session Configuration
      - SESSION_TIMEOUT_HOURS=8
      
      # Audit Log Configuration
      - AUDIT_LOG_RETENTION_DAYS=365
      
      # Admin User Configuration (optional)
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME:-Administrator}
      
      # Health Check Configuration
      - HEALTH_CHECK_ENABLED=true
      - HEALTH_CHECK_PATH=/health
      
    volumes:
      - envkey_data:/app/data
      - envkey_logs:/app/logs
    restart: unless-stopped
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check (overrides Dockerfile HEALTHCHECK)
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const req = http.get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }); req.on('error', () => process.exit(1)); req.setTimeout(5000, () => { req.destroy(); process.exit(1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  envkey_data:
    driver: local
  envkey_logs:
    driver: local