version: '3.8'

services:
  envkey-lite-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      # Application Configuration
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
      - APP_NAME=EnvKey Lite (Dev)
      - APP_VERSION=1.0.0-dev
      
      # Database Configuration
      - DATABASE_DIR=/app/data
      
      # Security Configuration (development keys)
      - JWT_SECRET=development-jwt-secret-with-minimum-32-characters-for-testing
      - ENCRYPTION_KEY=development-encryption-key-32-chars
      - API_KEY_PREFIX=envkey_dev_
      
      # CORS Configuration (permissive for development)
      - CORS_ORIGIN=*
      
      # Logging Configuration
      - LOG_LEVEL=debug
      
      # Rate Limiting (relaxed for development)
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=1000
      
      # Session Configuration
      - SESSION_TIMEOUT_HOURS=24
      
      # Audit Log Configuration
      - AUDIT_LOG_RETENTION_DAYS=30
      
      # Admin User Configuration
      - ADMIN_EMAIL=admin@localhost
      - ADMIN_PASSWORD=admin123
      - ADMIN_NAME=Development Admin
      
      # Health Check Configuration
      - HEALTH_CHECK_ENABLED=true
      - HEALTH_CHECK_PATH=/health
      
    volumes:
      - .:/app
      - /app/node_modules
      - envkey_dev_data:/app/data
      - envkey_dev_logs:/app/logs
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const req = http.get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }); req.on('error', () => process.exit(1)); req.setTimeout(5000, () => { req.destroy(); process.exit(1); });"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    command: npm run dev

volumes:
  envkey_dev_data:
    driver: local
  envkey_dev_logs:
    driver: local