# EnvKey Lite Monitoring Configuration

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================

logging:
  # Log levels: error, warn, info, debug, trace
  level: info
  
  # Log format: json, text
  format: json
  
  # Log outputs
  outputs:
    - type: console
      enabled: true
      format: text
    
    - type: file
      enabled: true
      path: /var/log/envkey-lite/app.log
      format: json
      rotation:
        max_size: 100MB
        max_files: 10
        compress: true
    
    - type: syslog
      enabled: false
      facility: local0
      tag: envkey-lite

  # Request logging
  requests:
    enabled: true
    exclude_paths:
      - /health
      - /metrics
    include_body: false
    include_headers: false

# =============================================================================
# METRICS CONFIGURATION
# =============================================================================

metrics:
  enabled: true
  
  # Metrics endpoint
  endpoint: /metrics
  
  # Prometheus format
  prometheus:
    enabled: true
    prefix: envkey_lite_
  
  # Custom metrics
  custom:
    - name: api_requests_total
      type: counter
      description: Total number of API requests
      labels: [method, endpoint, status]
    
    - name: api_request_duration_seconds
      type: histogram
      description: API request duration in seconds
      labels: [method, endpoint]
      buckets: [0.1, 0.5, 1, 2, 5, 10]
    
    - name: active_users
      type: gauge
      description: Number of active users
    
    - name: environment_variables_total
      type: gauge
      description: Total number of environment variables
      labels: [environment]
    
    - name: database_operations_total
      type: counter
      description: Total database operations
      labels: [operation, table]

# =============================================================================
# HEALTH CHECKS
# =============================================================================

health:
  enabled: true
  endpoint: /health
  
  checks:
    - name: database
      type: database
      timeout: 5s
      critical: true
    
    - name: disk_space
      type: disk
      path: /app/data
      threshold: 90%
      critical: true
    
    - name: memory
      type: memory
      threshold: 90%
      critical: false
    
    - name: api_response
      type: http
      url: http://localhost:3000/api
      timeout: 10s
      critical: true

# =============================================================================
# ALERTING
# =============================================================================

alerting:
  enabled: true
  
  # Alert channels
  channels:
    - name: email
      type: email
      config:
        smtp_host: smtp.your-domain.com
        smtp_port: 587
        smtp_user: alerts@your-domain.com
        smtp_password: your-password
        from: EnvKey Lite <alerts@your-domain.com>
        to: [admin@your-domain.com]
    
    - name: webhook
      type: webhook
      config:
        url: https://hooks.slack.com/your-webhook-url
        method: POST
        headers:
          Content-Type: application/json
  
  # Alert rules
  rules:
    - name: high_error_rate
      condition: error_rate > 0.05
      duration: 5m
      severity: critical
      channels: [email, webhook]
      message: "High error rate detected: {{ .Value }}"
    
    - name: database_connection_failed
      condition: database_health == false
      duration: 1m
      severity: critical
      channels: [email, webhook]
      message: "Database connection failed"
    
    - name: disk_space_low
      condition: disk_usage > 90
      duration: 10m
      severity: warning
      channels: [email]
      message: "Disk space usage is {{ .Value }}%"
    
    - name: memory_usage_high
      condition: memory_usage > 90
      duration: 15m
      severity: warning
      channels: [email]
      message: "Memory usage is {{ .Value }}%"

# =============================================================================
# PERFORMANCE MONITORING
# =============================================================================

performance:
  enabled: true
  
  # Sampling rate (0.0 to 1.0)
  sampling_rate: 0.1
  
  # Trace collection
  tracing:
    enabled: true
    service_name: envkey-lite
    
    # Jaeger configuration
    jaeger:
      endpoint: http://jaeger:14268/api/traces
      agent_host: jaeger
      agent_port: 6832
  
  # Profiling
  profiling:
    enabled: false
    cpu_profile_rate: 100
    memory_profile_rate: 512000

# =============================================================================
# AUDIT LOGGING
# =============================================================================

audit:
  enabled: true
  
  # Audit log retention
  retention:
    days: 365
    max_size: 1GB
  
  # Events to audit
  events:
    - user_login
    - user_logout
    - user_created
    - user_deleted
    - project_created
    - project_deleted
    - environment_created
    - environment_deleted
    - variable_created
    - variable_updated
    - variable_deleted
    - api_key_created
    - api_key_deleted
    - permission_granted
    - permission_revoked
  
  # Sensitive data filtering
  filter_sensitive: true
  sensitive_fields:
    - password
    - token
    - api_key
    - secret